### ISSUE TITLE
Student data overwrites the previous data

### ISSUE THREAD

**Issue by srujandeshpande** [acmpesuecc/AttendanceLogger#11]
### What happened?

When the program is run multiple times, the data entered overwrites the previous data stored in the file. It should append to the end of the `attendance.txt` file.

It might help to work on this issue after #10 is complete.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anirudhRowjee** [comment]
Go ahead @abhiraj2
