### ISSUE TITLE
Add functionality to view the attendance

### ISSUE THREAD

**Issue by srujandeshpande** [acmpesuecc/AttendanceLogger#13]
### What do you want to see?

Add a new feature that will print out the attendance from the file on the screen.

This issue depends on #12. If it has not been closed yet, you can implement a function for this which will be called by the code added in #12 later.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jxhnjj** [comment]
Can I work on this issue ?
